### ISSUE TITLE
DT monorepo conversion TODOs

### ISSUE THREAD

**Issue by jakebailey** [microsoft/DefinitelyTyped-tools#751]
This issue holds ongoing TODOs for the DT monorepo conversion, currently happening at https://github.com/jakebailey/DefinitelyTyped/tree/pnpm-workspaces-working.

```[tasklist]
### TODO
- [ ] Update dt-mergebot to not consider all `package.json` modification as needing maintainer review
- [ ] Update lint messages to mention `package.json` instead of the header
- [ ] Better explain `pnpm` usage in the README (installing subset of packages, need `-w` flag sometimes)
- [ ] Better explain the new package layout when creating new packages
- [ ] Update https://github.com/microsoft/dts-gen/pull/183
- [ ] Some sort of warning when pinning `@types/<...>` in a `package.json`
- [ ] Update GHA workflows
- [ ] Update checked-in pipelines
- [ ] Update UI-based pipelines (on-demand)
- [ ] Bikeshed names of fields in package.json (`typescriptVersion`)
- [ ] Document `pnpm run clean-node-modules` for Windows users
```

```[tasklist]
### Later TODO
- [ ] Make `index.d.ts` not required
- [ ] Allow `NodeNext` resolution
- [ ] Extend a base tsconfig instead of copy/pasting (may break partial clones)
- [ ] Orchestrate `test` with `pnpm`?
```
